dimail_ui_package_url: https://gitlab.mim-libre.fr/dimail/dimail-ui/-/package_files/3712/download
dimail_login_package_url: https://gitlab.mim-libre.fr/dimail/dimail-login/-/package_files/3606/download
dimail_login_version: v0.0.12-1
messagerie_server_container_tag: v0.3.8
