features:
  use_local_resolver: true
  # use_local_resolver: when true, bind9 will be installed on all the servers
  # and resolv.conf will be modified to use that local resolver. It reduces the
  # load on public DNS servers and is required for using public RBLs which are dns
  # based.
  use_custom_sshd_config: true
  # use_custom_sshd_config: when true, we will install a minimal sshd_config file
  # on all the servers, allwing only ssh connection with keys, and allowing only
  # few users (the default one, according to the hosting environment, and the user
  # 'api').
  # Whatever the value of this flag, we do check that the 'api' user is allowed to
  # connect, for managing the platform.
  use_s3_for_replication: true
  # use_s3_for_replication: when true, to setup the MySql replication, we will push
  # the dump on S3 (from master) and pull it from S3 (on slave).
  # When false, the dump will be pulled on the host running ansible (from master)
  # and then pushed to the slave.
  use_policyd_rate_limit: true
  # use_policyd_rate_limit: when true, policyd-rate-limit will be used, you need to
  # setup the variable with config elems in misc.yaml
  use_kopia_for_backup: true
  # use_kopia_for_backup: when true, will use kopia to make backups in an S3 bucket
  # it will be used to backup the mariadb dumps, and to make a full copy with
  # snapshots of the mailboxes
  use_rclone_for_backup: true
  # use_rclone_for_backup: when true, will use rclone to make backups in an S3 bucket
  # it will be used to backup the mariadb dumps, and to make a full copy of the
  # mailboxes
  use_dimail_plugins: false
  # use_dimail_plugins: when true, the plugins listed in the plugins variable will be
  # enabled on your platform
  use_external_ldap: false
  # use_external_ldap: when true, will install the ldap connectors for dovecot and
  # iterate on the ldap_domains for the configuration

default_webmail: "ox-7"
# By default, the plugins list is empty
plugins:
  web: []
