configdb_pwd: TOBEDEFINED
configdb_user: TOBEDEFINED
mysql_dovecot_pwd: TOBEDEFINED
mysql_api_pwd: TOBEDEFINED
mysql_postfix_pwd: TOBEDEFINED
mysql_opendkim_pwd: TOBEDEFINED
mysql_root_pwd: TOBEDEFINED
mysql_support_pwd: TOBEDEFINED
mysql_monitor_pwd: TOBEDEFINED
mysql_replication_pwd: TOBEDEFINED
mysql_prometheus_pwd: TOBEDEFINED
ldap_root_pwd: TOBEDEFINED
ldap_root_password: TOBEDEFINED
prom_pwd: TOBEDEFINED
prom_crypt: TOBEDEFINED
s3_credentials:
  your_s3_provider:
    region: TOBEDEFINEDLONGANDPAINFULL
    endpoint: TOBEDEFINEDLONGANDPAINFULL
    access_key: TOBEDEFINEDLONGANDPAINFULL
    secret_key: TOBEDEFINEDLONGANDPAINFULL
ox_master_username: TOBEDEFINED
ox_master_password: TOBEDEFINED
ox_admin_username: TOBEDEFINED
ox_admin_password: TOBEDEFINED
ox_cookie_salt: TOBEDEFINED
api_jwt_secret: TOBEDEFINED

