secrets:
  oidc_client_secret: TOBEDEFINED
  keycloak_keystore_password: TOBEDEFINED
  keycloak_admin_password: TOBEDEFINED


ox8_secrets:
  some-ox8-kube_app:
    password_secret: TOBEDEFINED
    basic_auth_login: TOBEDEFINED
    basic_auth_password: TOBEDEFINED
    credstorage_passcrypt: TOBEDEFINED
    hz_group_password: TOBEDEFINED
    jo_lokia_password: TOBEDEFINED
    cookie_hash_salt: TOBEDEFINED
    sessiond_encryptionKey: TOBEDEFINED
    share_cryptKey: TOBEDEFINED
    switchboard_api_secret: TOBEDEFINED
    switchboard_webhook_secret: TOBEDEFINED
    switchboard_signature_secret: TOBEDEFINED
    client_secret: TOBEDEFINED

