api_password:
  template:
    user: TOBEDEFINEDLONGENOUGH
    password: TOBEDEFINEDLONGENOUGH
  proxmoxdev:
    user: TOBEDEFINEDLONGENOUGH
    password: TOBEDEFINEDLONGENOUGH
  vspheredev:
    user: TOBEDEFINEDLONGENOUGH
    password: TOBEDEFINEDLONGENOUGH

