masters:
- platform: template
  master: TOBEDEFINEDWITHALONGUSERNAMEBECAUSEITWANTSTOBELONG
  pass: TOBEDEFINEDWITHALONGPASSWORDBECAUSEITWANTSTOBELONGTOO
- platform: proxmoxdev
  master: TOBEDEFINEDWITHALONGUSERNAMEBECAUSEITWANTSTOBELONG
  pass: TOBEDEFINEDWITHALONGPASSWORDBECAUSEITWANTSTOBELONGTOO

master: "{{ masters | selectattr('platform', 'equalto', env_name) | first }}"

